In [36]:
# Testing the geoapify replacement for google maps api since osm is washed
import pandas as pd
import requests
import time
import json

In [ ]:
df = pd.read_csv("data_2026-03-02_2026-03-08.csv")
# Filter out bad coordinates
df = df.dropna(subset = ['longitude', 'latitude'])
df = df[(df['longitude'] != 0) & (df['latitude'] != 0)]

# Clean and combine address data for later processing
df['street_name'] = df['street_name'].apply(lambda x : x.title())
df['address'] = df.apply(lambda x : str(x['house_number']) + ' ' + x['street_name'] ,axis = 1)

df = df.iloc[1:5]

df = df[
    ['inspection_type',
     'job_id',
     'job_progress',
     'house_number',
     'street_name',
     'address',
     'zip_code',
     'latitude',
     'longitude',
     'result',
     'approved_date',
     'nta'
     ]
]
df.head()

,inspection_type,job_id,job_progress,house_number,street_name,address,zip_code,latitude,longitude,result,approved_date,nta
2,Initial,PC8673353,1,88-47,187 Street,88-47 187 Street,11423.0,40.713865,-73.774740,Rat Activity,2026-03-03T14:36:31.000,Hollis
3,Initial,PC8671158,1,675,Riverside Drive,675 Riverside Drive,10031.0,40.826757,-73.952242,Failed for Rat Act,2026-03-04T09:46:11.000,Hamilton Heights-Sugar Hill
4,Initial,PC8672570,1,1603,President Street,1603 President Street,11213.0,40.667220,-73.935026,Failed for Other R,2026-03-03T08:42:22.000,Crown Heights (South)
5,Initial,PC8662766,1,768,Putnam Avenue,768 Putnam Avenue,11221.0,40.686198,-73.931088,Rat Activity,2026-03-03T10:14:31.000,Bedford-Stuyvesant (East)
6,Treatments,PC8589110,4,73,Steuben Street,73 Steuben Street,11205.0,40.695219,-73.963422,Bait applied,2026-03-02T13:38:21.000,Clinton Hill

In [ ]:
# import requests

# API methods

categories = "catering.restaurant,commercial.food_and_drink,catering.fast_food,catering.food_court,catering.bar"
longitude = str(-74.00961)
latitude = str(40.71525)
radius = "50"
max_locations_returned = "5"


# url = f"https://api.geoapify.com/v2/places?categories=catering.restaurant,commercial.food_and_drink,catering.fast_food,catering.food_court,catering.bar&filter=circle:-74.00961946500342,40.71525406412272,50&bias=proximity:-74.00961946500342,40.71525406412272&limit=5&apiKey={geoapify_key}"

url = f"https://api.geoapify.com/v2/places?categories={categories}&filter=circle:{longitude},{latitude},{radius}&bias=proximity:{longitude},{latitude}&limit={max_locations_returned}&apiKey={geoapify_key}"
payload = {}
headers = {}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

{"type":"FeatureCollection","features":[{"type":"Feature","properties":{"name":"JR Sushi 2","country":"United States","country_code":"us","state":"New York","county":"New York County","city":"New York","postcode":"10007","district":"Tribeca","suburb":"Manhattan","quarter":"Lower Manhattan","street":"West Broadway","housenumber":"86A","iso3166_2":"US-NY","lon":-74.009614,"lat":40.7152802,"state_code":"NY","formatted":"JR Sushi 2, 86A West Broadway, New York, NY 10007, United States of America","address_line1":"JR Sushi 2","address_line2":"86A West Broadway, New York, NY 10007, United States of America","categories":["catering","catering.restaurant","catering.restaurant.sushi"],"details":["details","details.catering","details.contact"],"datasource":{"sourcename":"openstreetmap","attribution":"© OpenStreetMap contributors","license":"Open Database License","url":"https://www.openstreetmap.org/copyright","raw":{"name":"JR Sushi 2","phone":"+1-212-233-8338","osm_id":2641379134,"amenity":"restaurant","cuisine":"sushi","website":"http://jrsushi.com/","osm_type":"n","check_date":"2023-07-31","addr:street":"West Broadway","addr:postcode":10007,"addr:housenumber":"86A"}},"website":"http://jrsushi.com/","contact":{"phone":"+1-212-233-8338"},"catering":{"cuisine":"sushi"},"distance":3,"place_id":"515be509849d8052c0596702364d8e5b4440f00103f9013e3f709d0000000092030a4a522053757368692032"},"geometry":{"type":"Point","coordinates":[-74.00961399999998,40.715280200359125]}},{"type":"Feature","properties":{"name":"Galerie Bar","country":"United States","country_code":"us","state":"New York","county":"New York County","city":"New York","postcode":"10012","district":"Tribeca","suburb":"Manhattan","quarter":"Lower Manhattan","street":"West Broadway","iso3166_2":"US-NY","lon":-74.0092889,"lat":40.7151386,"state_code":"NY","formatted":"Galerie Bar, West Broadway, New York, NY 10012, United States of America","address_line1":"Galerie Bar","address_line2":"West Broadway, New York, NY 10012, United States of America","categories":["catering","catering.bar"],"details":[],"datasource":{"sourcename":"openstreetmap","attribution":"© OpenStreetMap contributors","license":"Open Database License","url":"https://www.openstreetmap.org/copyright","raw":{"name":"Galerie Bar","osm_id":11079239445,"amenity":"bar","osm_type":"n","check_date":"2023-07-31"}},"distance":30,"place_id":"51d06d7830988052c059265362a9895b4440f00103f90115c75f940200000092030b47616c6572696520426172"},"geometry":{"type":"Point","coordinates":[-74.0092889,40.71513860035911]}},{"type":"Feature","properties":{"name":"The Smyth","country":"United States","country_code":"us","state":"New York","county":"New York County","city":"New York","postcode":"10012","district":"Tribeca","suburb":"Manhattan","quarter":"Lower Manhattan","street":"West Broadway","iso3166_2":"US-NY","lon":-74.0091966,"lat":40.7152376,"state_code":"NY","formatted":"The Smyth, West Broadway, New York, NY 10012, United States of America","address_line1":"The Smyth","address_line2":"West Broadway, New York, NY 10012, United States of America","categories":["catering","catering.restaurant"],"details":["details.catering","details.facilities"],"datasource":{"sourcename":"openstreetmap","attribution":"© OpenStreetMap contributors","license":"Open Database License","url":"https://www.openstreetmap.org/copyright","raw":{"name":"The Smyth","level":0,"osm_id":11079239444,"amenity":"restaurant","osm_type":"n","check_date":"2023-07-31","indoor_seating":"yes","outdoor_seating":"yes"}},"facilities":{"outdoor_seating":true},"distance":35,"place_id":"51010f56ad968052c059bb34dbe78c5b4440f00103f90114c75f940200000092030954686520536d797468"},"geometry":{"type":"Point","coordinates":[-74.00919660000001,40.715237600359124]}},{"type":"Feature","properties":{"name":"Mulberry & Vine","country":"United States","country_code":"us","state":"New York","county":"New York County","city":"New York","postcode":"10007","district":"Tribeca","suburb":"Manhattan","quarter":"Lower Manhattan","street":"Warren Street","housenumber":"73","iso3166_2":"US-NY","lon":-74.0102094,"lat":40.7149828,"state_code":"NY","formatted":"Mulberry & Vine, 73 Warren Street, New York, NY 10007, United States of America","address_line1":"Mulberry & Vine","address_line2":"73 Warren Street, New York, NY 10007, United States of America","categories":["building","building.catering","catering","catering.restaurant","catering.restaurant.american","wheelchair","wheelchair.yes"],"details":["details","details.building","details.catering","details.contact","details.facilities"],"datasource":{"sourcename":"openstreetmap","attribution":"© OpenStreetMap contributors","license":"Open Database License","url":"https://www.openstreetmap.org/copyright","raw":{"name":"Mulberry & Vine","phone":"+1-212-791-6300","height":22.1,"osm_id":277890498,"amenity":"restaurant","cuisine":"american","website":"https://www.mulberryandvine.com/","building":"yes","osm_type":"w","addr:city":"New York","wheelchair":"yes","addr:street":"Warren Street","addr:postcode":10007,"addr:housenumber":73}},"website":"https://www.mulberryandvine.com/","contact":{"phone":"+1-212-791-6300"},"facilities":{"wheelchair":true},"catering":{"cuisine":"american"},"building":{"height":22.1},"distance":48,"place_id":"5142372e45a78052c0598aff048e845b4440f00102f901c24590100000000092030f4d756c626572727920262056696e65"},"geometry":{"type":"Point","coordinates":[-74.01020936501757,40.714982750359084]}}]}

In [55]:
res = json.loads(response.text)

df = pd.DataFrame([
    {
        **feature["properties"],
        "geo_lon": feature["geometry"]["coordinates"][0],
        "geo_lat": feature["geometry"]["coordinates"][1],
    }
    for feature in res["features"]
])
print(df.columns)
selected_columns = ['name', 'county', 'city', 'postcode', 'district', 'suburb', 'quarter', 'street', 'housenumber','lon','lat', 'formatted', 'catering']
df = df[selected_columns]
df

Index(['name', 'country', 'country_code', 'state', 'county', 'city',
       'postcode', 'district', 'suburb', 'quarter', 'street', 'housenumber',
       'iso3166_2', 'lon', 'lat', 'state_code', 'formatted', 'address_line1',
       'address_line2', 'categories', 'details', 'datasource', 'website',
       'contact', 'catering', 'distance', 'place_id', 'geo_lon', 'geo_lat',
       'facilities', 'building'],
      dtype='object')

,name,county,city,postcode,district,suburb,quarter,street,housenumber,lon,lat,formatted,catering
0,JR Sushi 2,New York County,New York,10007,Tribeca,Manhattan,Lower Manhattan,West Broadway,86A,-74.009614,40.715280,"JR Sushi 2, 86A West Broadway, New York, NY 10...",{'cuisine': 'sushi'}
1,Galerie Bar,New York County,New York,10012,Tribeca,Manhattan,Lower Manhattan,West Broadway,NaN,-74.009289,40.715139,"Galerie Bar, West Broadway, New York, NY 10012...",NaN
2,The Smyth,New York County,New York,10012,Tribeca,Manhattan,Lower Manhattan,West Broadway,NaN,-74.009197,40.715238,"The Smyth, West Broadway, New York, NY 10012, ...",NaN
3,Mulberry & Vine,New York County,New York,10007,Tribeca,Manhattan,Lower Manhattan,Warren Street,73,-74.010209,40.714983,"Mulberry & Vine, 73 Warren Street, New York, N...",{'cuisine': 'american'}

In [ ]:

categories = "catering.restaurant,commercial.food_and_drink,catering.fast_food,catering.food_court,catering.bar"
radius = "50"
max_locations_returned = "5"

all_restaurants_df = pd.DataFrame()

for _ , row in df.iterrows():

    time.sleep(2)
    longitude = str(row['longitude'])
    latitude = str(row['latitude'])

    url = f"https://api.geoapify.com/v2/places?categories={categories}&filter=circle:{longitude},{latitude},{radius}&bias=proximity:{longitude},{latitude}&limit={max_locations_returned}&apiKey={geoapify_key}"

    payload = {}
    headers = {}

    response = requests.request("GET", url, headers=headers, data=payload)

    res = json.loads(response.text)
    print(res)
    try:
        local_restaurant_df = pd.DataFrame([
            {
                **feature["properties"],
                "geo_lon": feature["geometry"]["coordinates"][0],
                "geo_lat": feature["geometry"]["coordinates"][1],
            }
            for feature in res["features"]
        ])
        
        # selected_columns = ['name', 'county', 'city', 'postcode', 'district', 'suburb', 'quarter', 'street', 'housenumber','lon','lat', 'formatted', 'catering']
        # local_restaurant_df = local_restaurant_df[selected_columns]
        
        all_restaurants_df = pd.concat([all_restaurants_df, local_restaurant_df])
    except Exception as e:
        print(e)
        # Move on if no data is found
        continue

{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'properties': {'name': 'Hello, Yam!', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'New York County', 'city': 'New York', 'postcode': '10009', 'district': 'East Village', 'suburb': 'Manhattan', 'street': 'East 9th Street', 'housenumber': '4432', 'iso3166_2': 'US-NY', 'lon': -73.9829136, 'lat': 40.727499, 'state_code': 'NY', 'formatted': 'Hello, Yam!, 4432 East 9th Street, New York, NY 10009, United States of America', 'address_line1': 'Hello, Yam!', 'address_line2': '4432 East 9th Street, New York, NY 10009, United States of America', 'categories': ['catering', 'catering.fast_food', 'vegan'], 'details': ['details', 'details.catering', 'details.contact'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Hello, Yam!', 'email': 'eastvillage@helloyamnyc.com', 'phone': '+1-347-222-6434', 'osm_id': 12247152956, 'amenity': 'fast_food', 'cuisine': 'japanese;sweet_potato', 'website': 'https://www.helloyam.com/', 'osm_type': 'n', 'addr:city': 'New York', 'addr:state': 'NY', 'diet:vegan': 'yes', 'addr:street': 'East 9th Street', 'website:menu': 'https://www.helloyam.com/menu', 'addr:postcode': 10009, 'addr:housenumber': 4432, 'contact:instagram': 'helloyam_eastvillage'}}, 'website': 'https://www.helloyam.com/', 'contact': {'phone': '+1-347-222-6434', 'email': 'eastvillage@helloyamnyc.com'}, 'catering': {'cuisine': 'japanese;sweet_potato', 'diet': {'vegan': True}}, 'distance': 14, 'place_id': '51cbb2710ee87e52c059f235efaf1e5d4440f00103f9013cb9fcd90200000092030b48656c6c6f2c2059616d21'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9829136, 40.727499000360595]}}, {'type': 'Feature', 'properties': {'name': 'Confectionery!', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'New York County', 'city': 'New York', 'postcode': '10003', 'district': 'East Village', 'suburb': 'Manhattan', 'street': 'East 9th Street', 'housenumber': '440', 'iso3166_2': 'US-NY', 'lon': -73.9830755, 'lat': 40.7273195, 'state_code': 'NY', 'formatted': 'Confectionery!, 440 East 9th Street, New York, NY 10003, United States of America', 'address_line1': 'Confectionery!', 'address_line2': '440 East 9th Street, New York, NY 10003, United States of America', 'categories': ['commercial', 'commercial.food_and_drink', 'commercial.food_and_drink.bakery', 'vegan', 'vegetarian'], 'details': ['details', 'details.contact'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Confectionery!', 'shop': 'bakery', 'phone': '+1 646-869-0133', 'osm_id': 6281164644, 'website': 'https://lagustasluscious.com/shop/', 'osm_type': 'n', 'diet:vegan': 'yes', 'addr:street': 'East 9th Street', 'description': 'Vegan sweet shop.', 'opening_hours': 'Mo-Su 12:00-15:30, Mo-Sa 16:15-20:00', 'diet:vegetarian': 'yes', 'addr:housenumber': 440}}, 'website': 'https://lagustasluscious.com/shop/', 'opening_hours': 'Mo-Su 12:00-15:30, Mo-Sa 16:15-20:00', 'description': 'Vegan sweet shop.', 'contact': {'phone': '+1 646-869-0133'}, 'commercial': {'type': 'bakery'}, 'distance': 14, 'place_id': '51ec7f80b5ea7e52c05957e52dce185d4440f00103f90164f762760100000092030e436f6e66656374696f6e65727921'}, 'geometry': {'type': 'Point', 'coordinates': [-73.98307549999998, 40.72731950036057]}}, {'type': 'Feature', 'properties': {'name': 'Doc Hollidays', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'New York County', 'city': 'New York', 'postcode': '10009', 'district': 'Alphabet City', 'suburb': 'Manhattan', 'street': 'Avenue A', 'housenumber': '141', 'iso3166_2': 'US-NY', 'lon': -73.982885, 'lat': 40.7272283, 'state_code': 'NY', 'formatted': 'Doc Hollidays, 141 Avenue A, New York, NY 10009, United States of America', 'address_line1': 'Doc Hollidays', 'address_line2': '141 Avenue A, New York, NY 10009, United States of America', 'categories': ['catering', 'catering.bar'], 'details': [], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Doc Hollidays', 'osm_id': 2549928461, 'amenity': 'bar', 'osm_type': 'n', 'check_date': '2024-11-09', 'addr:street': 'Avenue A', 'addr:postcode': 10009, 'addr:housenumber': 141, 'opening_hours:signed': 'no'}}, 'distance': 17, 'place_id': '51a6ae7c96e77e52c059196323d1155d4440f00103f9010dd2fc970000000092030d446f6320486f6c6c6964617973'}, 'geometry': {'type': 'Point', 'coordinates': [-73.98288499999998, 40.727228300360544]}}, {'type': 'Feature', 'properties': {'name': "Poke N' Roll", 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'New York County', 'city': 'New York', 'postcode': '10009', 'district': 'East Village', 'suburb': 'Manhattan', 'street': 'East 9th Street', 'housenumber': '441', 'iso3166_2': 'US-NY', 'lon': -73.9830427, 'lat': 40.7275413, 'state_code': 'NY', 'formatted': "Poke N' Roll, 441 East 9th Street, New York, NY 10009, United States of America", 'address_line1': "Poke N' Roll", 'address_line2': '441 East 9th Street, New York, NY 10009, United States of America', 'categories': ['catering', 'catering.fast_food'], 'details': ['details', 'details.catering', 'details.contact', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': "Poke N' Roll", 'phone': '+1-212-420-7653', 'osm_id': 7366142883, 'amenity': 'fast_food', 'cuisine': 'hawaiian', 'osm_type': 'n', 'takeaway': 'yes', 'addr:street': 'East 9th Street', 'addr:postcode': 10009, 'opening_hours': 'Mo-Su 11:00-22:00', 'addr:housenumber': 441, 'contact:facebook': 'https://www.facebook.com/pokenrollnyc/'}}, 'opening_hours': 'Mo-Su 11:00-22:00', 'contact': {'phone': '+1-212-420-7653'}, 'facilities': {'takeaway': True}, 'catering': {'cuisine': 'hawaiian'}, 'distance': 20, 'place_id': '5194c4ed2bea7e52c059dec4c512205d4440f00103f901a36b0eb70100000092030c506f6b65204e2720526f6c6c'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9830427, 40.727541300360585]}}, {'type': 'Feature', 'properties': {'name': 'Tacos Morelos', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'New York County', 'city': 'New York', 'postcode': '10009', 'district': 'East Village', 'suburb': 'Manhattan', 'street': 'East 9th Street', 'housenumber': '438', 'iso3166_2': 'US-NY', 'lon': -73.9831865, 'lat': 40.7273626, 'state_code': 'NY', 'formatted': 'Tacos Morelos, 438 East 9th Street, New York, NY 10009, United States of America', 'address_line1': 'Tacos Morelos', 'address_line2': '438 East 9th Street, New York, NY 10009, United States of America', 'categories': ['catering', 'catering.fast_food'], 'details': ['details', 'details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Tacos Morelos', 'osm_id': 5215491822, 'amenity': 'fast_food', 'delivery': 'yes', 'osm_type': 'n', 'takeaway': 'yes', 'addr:street': 'East 9th Street', 'addr:postcode': 10009, 'opening_hours': 'Mo-Su 11:00-22:30', 'addr:housenumber': 438}}, 'opening_hours': 'Mo-Su 11:00-22:30', 'facilities': {'takeaway': True, 'delivery': True}, 'distance': 21, 'place_id': '5199d71187ec7e52c059ea70ba371a5d4440f00103f901ee16de360100000092030d5461636f73204d6f72656c6f73'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9831865, 40.727362600360564]}}]}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'properties': {'name': 'Diyaanaat NY', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Queens County', 'city': 'New York', 'postcode': '11432', 'suburb': 'Queens', 'street': '160th Street', 'housenumber': '160-02', 'iso3166_2': 'US-NY', 'lon': -73.8016116, 'lat': 40.7076871, 'state_code': 'NY', 'formatted': 'Diyaanaat NY, 160-02 160th Street, New York, NY 11432, United States of America', 'address_line1': 'Diyaanaat NY', 'address_line2': '160-02 160th Street, New York, NY 11432, United States of America', 'categories': ['commercial', 'commercial.food_and_drink', 'commercial.food_and_drink.butcher'], 'details': ['details.commercial', 'details.contact'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Diyaanaat NY', 'shop': 'butcher', 'level': 0, 'phone': '+1-917-515-0652', 'osm_id': 9815263219, 'osm_type': 'n', 'addr:city': 'Jamaica', 'addr:state': 'NY', 'addr:street': '160th Street', 'addr:postcode': 11432, 'addr:housenumber': '160-02'}}, 'contact': {'phone': '+1-917-515-0652'}, 'commercial': {'type': 'butcher', 'level': 0}, 'distance': 24, 'place_id': '510786bd9a4d7352c05978ebab7d955a4440f00103f901f30709490200000092030c44697961616e616174204e59'}, 'geometry': {'type': 'Point', 'coordinates': [-73.80161159999999, 40.707687100358214]}}, {'type': 'Feature', 'properties': {'name': "Sybil's Restaurant & Bakery", 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Queens County', 'city': 'New York', 'postcode': '11432', 'suburb': 'Queens', 'street': 'Hillside Avenue', 'housenumber': '159-24', 'iso3166_2': 'US-NY', 'lon': -73.801885, 'lat': 40.7078089, 'state_code': 'NY', 'formatted': "Sybil's Restaurant & Bakery, 159-24 Hillside Avenue, New York, NY 11432, United States of America", 'address_line1': "Sybil's Restaurant & Bakery", 'address_line2': '159-24 Hillside Avenue, New York, NY 11432, United States of America', 'categories': ['catering', 'catering.restaurant'], 'details': ['details', 'details.catering', 'details.contact', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': "Sybil's Restaurant & Bakery", 'phone': '+1-718-297-2359', 'osm_id': 4964211688, 'amenity': 'restaurant', 'website': 'https://www.sybilsbakerynyc.com', 'osm_type': 'n', 'addr:city': 'Jamaica', 'addr:state': 'NY', 'addr:street': 'Hillside Avenue', 'addr:postcode': 11432, 'opening_hours': '10:00-21:00', 'indoor_seating': 'yes', 'outdoor_seating': 'no', 'addr:housenumber': '159-24', 'air_conditioning': 'yes'}}, 'website': 'https://www.sybilsbakerynyc.com', 'opening_hours': '10:00-21:00', 'contact': {'phone': '+1-718-297-2359'}, 'facilities': {'air_conditioning': True, 'outdoor_seating': False}, 'distance': 44, 'place_id': '51ca897615527352c0599b6d677b995a4440f00103f901e8dbe3270100000092031b537962696c27732052657374617572616e7420262042616b657279'}, 'geometry': {'type': 'Point', 'coordinates': [-73.801885, 40.70780890035822]}}]}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': []}
{'type': 'FeatureCollection', 'features': [{'type': 'Feature', 'properties': {'name': 'Tipsy', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Kings County', 'city': 'New York', 'postcode': '11205', 'suburb': 'Brooklyn', 'street': 'Myrtle Avenue', 'housenumber': '584', 'iso3166_2': 'US-NY', 'lon': -73.9612384, 'lat': 40.6938754, 'state_code': 'NY', 'formatted': 'Tipsy, 584 Myrtle Avenue, New York, NY 11205, United States of America', 'address_line1': 'Tipsy', 'address_line2': '584 Myrtle Avenue, New York, NY 11205, United States of America', 'categories': ['commercial', 'commercial.food_and_drink', 'commercial.food_and_drink.drinks'], 'details': ['details', 'details.contact'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Tipsy', 'shop': 'alcohol', 'phone': '+1-347-599-1672', 'osm_id': 9583789838, 'website': 'https://shoptipsy.com', 'osm_type': 'n', 'drink:wine': 'yes', 'addr:street': 'Myrtle Avenue', 'drink:liquor': 'yes', 'addr:postcode': 11205, 'opening_hours': 'Mo-Th 15:00-21:00; Fr-Sa 12:00-22:00; Su 12:00-21:00', 'addr:housenumber': 584}}, 'website': 'https://shoptipsy.com', 'opening_hours': 'Mo-Th 15:00-21:00; Fr-Sa 12:00-22:00; Su 12:00-21:00', 'contact': {'phone': '+1-347-599-1672'}, 'commercial': {'type': 'alcohol'}, 'distance': 11, 'place_id': '5133ea10ee847d52c059e003bce8d0584440f00103f9010e073d3b020000009203055469707379'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9612384, 40.693875400356546]}}, {'type': 'Feature', 'properties': {'name': 'Moot Bar', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Kings County', 'city': 'New York', 'postcode': '11205', 'suburb': 'Brooklyn', 'street': 'Myrtle Avenue', 'housenumber': '579', 'iso3166_2': 'US-NY', 'lon': -73.960971, 'lat': 40.6941319, 'state_code': 'NY', 'formatted': 'Moot Bar, 579 Myrtle Avenue, New York, NY 11205, United States of America', 'address_line1': 'Moot Bar', 'address_line2': '579 Myrtle Avenue, New York, NY 11205, United States of America', 'categories': ['catering', 'catering.bar'], 'details': ['details', 'details.catering', 'details.contact', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Moot Bar', 'phone': '+1-718-638-3982', 'osm_id': 5772062970, 'amenity': 'bar', 'smoking': 'no', 'website': 'https://www.mootbar.com', 'osm_type': 'n', 'addr:city': 'Brooklyn', 'addr:state': 'NY', 'addr:street': 'Myrtle Avenue', 'addr:postcode': 11205, 'opening_hours': 'Mo-Th 15:00-02:00; Fr-Sa 15:00-04:00; Su 15:00-02:00', 'outdoor_seating': 'sidewalk', 'addr:housenumber': 579}}, 'website': 'https://www.mootbar.com', 'opening_hours': 'Mo-Th 15:00-02:00; Fr-Sa 15:00-04:00; Su 15:00-02:00', 'contact': {'phone': '+1-718-638-3982'}, 'facilities': {'smoking': False, 'outdoor_seating': True}, 'distance': 30, 'place_id': '51e259828c807d52c05928926950d9584440f00103f901fab00a58010000009203084d6f6f7420426172'}, 'geometry': {'type': 'Point', 'coordinates': [-73.960971, 40.69413190035658]}}, {'type': 'Feature', 'properties': {'name': "Nathan's", 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Kings County', 'city': 'New York', 'postcode': '11205', 'suburb': 'Brooklyn', 'street': 'Myrtle Avenue', 'housenumber': '569', 'iso3166_2': 'US-NY', 'lon': -73.9615527, 'lat': 40.6941544, 'state_code': 'NY', 'formatted': "Nathan's, 569 Myrtle Avenue, New York, NY 11205, United States of America", 'address_line1': "Nathan's", 'address_line2': '569 Myrtle Avenue, New York, NY 11205, United States of America', 'categories': ['catering', 'catering.fast_food', 'catering.fast_food.hot_dog'], 'details': ['details', 'details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': "Nathan's", 'brand': "Nathan's", 'osm_id': 7173294497, 'amenity': 'fast_food', 'cuisine': 'hot_dog', 'osm_type': 'n', 'takeaway': 'yes', 'ice_cream': 'yes', 'drink:coffee': 'yes', 'brand:wikidata': 'Q1319505'}}, 'brand': "Nathan's", 'brand_details': {'wikidata': 'Q1319505'}, 'facilities': {'takeaway': True}, 'catering': {'cuisine': 'hot_dog'}, 'distance': 32, 'place_id': '515af855148a7d52c059f8f3270dda584440f00103f901a1c98fab010000009203084e617468616e2773'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9615527, 40.69415440035658]}}, {'type': 'Feature', 'properties': {'name': 'The Emerson', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Kings County', 'city': 'New York', 'postcode': '11205', 'suburb': 'Brooklyn', 'street': 'Myrtle Avenue', 'housenumber': '561', 'iso3166_2': 'US-NY', 'lon': -73.9618019, 'lat': 40.6940535, 'state_code': 'NY', 'formatted': 'The Emerson, 561 Myrtle Avenue, New York, NY 11205, United States of America', 'address_line1': 'The Emerson', 'address_line2': '561 Myrtle Avenue, New York, NY 11205, United States of America', 'categories': ['catering', 'catering.bar'], 'details': ['details.catering', 'details.facilities'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'The Emerson', 'sport': 'billiards', 'osm_id': 9583805198, 'amenity': 'bar', 'osm_type': 'n', 'drink:beer': 'draught', 'outdoor_seating': 'garden;street'}}, 'facilities': {'outdoor_seating': True}, 'distance': 47, 'place_id': '51c26e8e298e7d52c05957dabebed6584440f00103f9010e433d3b0200000092030b54686520456d6572736f6e'}, 'geometry': {'type': 'Point', 'coordinates': [-73.96180189999998, 40.69405350035657]}}, {'type': 'Feature', 'properties': {'name': 'Kingston Bakery Brooklyn', 'country': 'United States', 'country_code': 'us', 'state': 'New York', 'county': 'Kings County', 'city': 'New York', 'postcode': '11205', 'suburb': 'Brooklyn', 'street': 'Myrtle Avenue', 'housenumber': '585', 'iso3166_2': 'US-NY', 'lon': -73.9607348, 'lat': 40.6941607, 'state_code': 'NY', 'formatted': 'Kingston Bakery Brooklyn, 585 Myrtle Avenue, New York, NY 11205, United States of America', 'address_line1': 'Kingston Bakery Brooklyn', 'address_line2': '585 Myrtle Avenue, New York, NY 11205, United States of America', 'categories': ['catering', 'catering.fast_food'], 'details': ['details.catering', 'details.contact'], 'datasource': {'sourcename': 'openstreetmap', 'attribution': '© OpenStreetMap contributors', 'license': 'Open Database License', 'url': 'https://www.openstreetmap.org/copyright', 'raw': {'name': 'Kingston Bakery Brooklyn', 'phone': '+1-347-406-9555', 'osm_id': 9583753112, 'amenity': 'fast_food', 'cuisine': 'jamaican', 'osm_type': 'n'}}, 'contact': {'phone': '+1-347-406-9555'}, 'catering': {'cuisine': 'jamaican'}, 'distance': 49, 'place_id': '514388d0ad7c7d52c05998190142da584440f00103f90198773c3b020000009203184b696e6773746f6e2042616b6572792042726f6f6b6c796e'}, 'geometry': {'type': 'Point', 'coordinates': [-73.9607348, 40.694160700356576]}}]}
{'type': 'FeatureCollection', 'features': []}

In [84]:
print(all_restaurants_df.columns)
all_restaurants_df.head()

Index(['name', 'country', 'country_code', 'state', 'county', 'city',
       'postcode', 'district', 'suburb', 'street', 'housenumber', 'iso3166_2',
       'lon', 'lat', 'state_code', 'formatted', 'address_line1',
       'address_line2', 'categories', 'details', 'datasource', 'website',
       'contact', 'catering', 'distance', 'place_id', 'geo_lon', 'geo_lat',
       'opening_hours', 'description', 'commercial', 'facilities', 'brand',
       'brand_details', 'quarter', 'building', 'name_other'],
      dtype='object')

,name,country,country_code,state,county,city,postcode,district,suburb,street,...,geo_lat,opening_hours,description,commercial,facilities,brand,brand_details,quarter,building,name_other
0,"Hello, Yam!",United States,us,New York,New York County,New York,10009,East Village,Manhattan,East 9th Street,...,40.727499,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Confectionery!,United States,us,New York,New York County,New York,10003,East Village,Manhattan,East 9th Street,...,40.727320,"Mo-Su 12:00-15:30, Mo-Sa 16:15-20:00",Vegan sweet shop.,{'type': 'bakery'},NaN,NaN,NaN,NaN,NaN,NaN
2,Doc Hollidays,United States,us,New York,New York County,New York,10009,Alphabet City,Manhattan,Avenue A,...,40.727228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Poke N' Roll,United States,us,New York,New York County,New York,10009,East Village,Manhattan,East 9th Street,...,40.727541,Mo-Su 11:00-22:00,NaN,NaN,{'takeaway': True},NaN,NaN,NaN,NaN,NaN
4,Tacos Morelos,United States,us,New York,New York County,New York,10009,East Village,Manhattan,East 9th Street,...,40.727363,Mo-Su 11:00-22:30,NaN,NaN,"{'takeaway': True, 'delivery': True}",NaN,NaN,NaN,NaN,NaN

In [86]:
selected_columns = ['name', 'county', 'city', 'postcode', 'district', 'suburb', 'housenumber', 'street', 'lon','lat', 'formatted', 'catering', 'commercial']
geo_rest_df = all_restaurants_df[selected_columns]

In [88]:
pd.merge(left = df, right = geo_rest_df, how = "inner", left_on = ['house_number', 'street_name'], right_on = ['housenumber', 'street'])

,inspection_type,job_id,job_progress,house_number,street_name,address,zip_code,latitude,longitude,result,...,postcode,district,suburb,housenumber,street,lon,lat,formatted,catering,commercial
0,Treatments,PC8488952,7,584,Myrtle Avenue,584 Myrtle Avenue,11205.0,40.693975,-73.961259,Bait applied,...,11205,NaN,Brooklyn,584,Myrtle Avenue,-73.961238,40.693875,"Tipsy, 584 Myrtle Avenue, New York, NY 11205, ...",NaN,{'type': 'alcohol'}
1,Initial,PC8666642,1,188,Wilson Avenue,188 Wilson Avenue,11237.0,40.699379,-73.923425,Rat Activity,...,11207,NaN,Brooklyn,188,Wilson Avenue,-73.923511,40.699303,"Happy Garden, 188 Wilson Avenue, New York, NY ...",{'cuisine': 'chinese'},NaN
2,Initial,PC8666642,1,188,Wilson Avenue,188 Wilson Avenue,11237.0,40.699379,-73.923425,Rat Activity,...,11207,NaN,Brooklyn,188,Wilson Avenue,-73.923511,40.699303,"Happy Garden, 188 Wilson Avenue, New York, NY ...",{'cuisine': 'chinese'},NaN